{% set name = "Vulkan-Loader" %}
{% set version = "1.3.216.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/{{ name }}/archive/refs/tags/sdk-{{ version }}.tar.gz
  sha256: 46188d3db019409b82f850628d5c175cc59dcdb3ce146f5c023b97709f67e8f1

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - vulkan-headers {{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libvulkan.dylib  # [osx]
    - test -f ${PREFIX}/lib/libvulkan.so  # [linux]
    - if not exist %PREFIX%\\Library\\Release\\libvulkan.dll exit 1 # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Loader
  summary: 'This project provides the Khronos official Vulkan ICD desktop loader'
  description: |
    Vulkan is an explicit API, enabling direct control over how GPUs actually work.
    As such, Vulkan supports systems that have multiple GPUs, each running with a
    different driver, or ICD (Installable Client Driver). Vulkan also supports
    multiple global contexts (instances, in Vulkan terminology). The ICD loader is
    a library that is placed between a Vulkan application and any number of Vulkan
    drivers, in order to support multiple drivers and the instance-level
    functionality that works across these drivers.
    Additionally, the loader manages inserting Vulkan layer libraries, such as
    validation layers, between an application and the drivers.
    This repository contains the Vulkan loader that is used for Linux, Windows,
    MacOS, and iOS. There is also a separate loader, maintained by Google,
    which is used on Android.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  # The doc_url and dev_url are optional.
  doc_url: https://vulkan.lunarg.com/doc/sdk
  dev_url: https://github.com/KhronosGroup/Vulkan-Loader

extra:
  recipe-maintainers:
    - jave27
